name: node-api-spec-boilerplate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update version - patch
      if: github.ref == 'refs/heads/main'
      env:
        GIT_USER_NAME: '${{ secrets.GIT_USER_NAME }}'
        GIT_USER_EMAIL: '${{ secrets.GIT_USER_EMAIL }}'
      id: update_version
      run: |
          version=$(npm version patch)
          echo $version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add package.json
          git commit -m "[AUTO-COMMIT] Update to version ${{ version }} [ci skip]"
          git push origin main
    - name: Build
      run: |
        yarn --frozen-lockfile
        npm run build
    - name: Upload Spec
      uses: actions/upload-artifact@v2
      with:
        name: swagger-spec
        path: dist/generated/swagger.json
    - name: Upload Spec To Hub
      env:
        SWAGGERHUB_API_KEY: '${{ secrets.SWAGGERHUB_API_KEY }}'
      if: github.ref == 'refs/heads/main'
      run: |
        npx swaggerhub-cli api:create haimkastner/node-api-spec-boilerplate --file dist/generated/swagger.json --published=publish --visibility=public --setdefault
